### ISSUE TITLE
Broken link formation during install 

### ISSUE THREAD

**Issue by shishironline** [syscolabs/kasaya#10]
while installing, broken link /usr/bin/kasaya -> usr/lib/node_modules/kasaya/kasaya.js as no folder ‘kasaya’ in /usr/lib/node_modules created
Ubuntu Linux 19.10
terminal output:
sudo npm install -g kasaya
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/bin/kasaya -> /usr/lib/node_modules/kasaya/kasaya.js

> core-js-pure@3.6.4 postinstall /usr/lib/node_modules/kasaya/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> kasaya@0.1.1 postinstall /usr/lib/node_modules/kasaya
> ./scripts/postinstall.js

installing selenium and browser drivers. please wait...
Error while setting up Selenium or Browser driver: EACCES: permission denied, mkdir '/usr/lib/node_modules/kasaya/node_modules/selenium-standalone/.selenium'
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! kasaya@0.1.1 postinstall: `./scripts/postinstall.js`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the kasaya@0.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-20T18_08_02_430Z-debug.log

**Comment by AshanthaLahiru** [comment]
Thank you for the feedback, closing this issue since duplicate #8
