### ISSUE TITLE
accept open argument

### ISSUE THREAD

**Issue by delanym** [syscolabs/kasaya#16]
Would be nice to start with a URL
`nodejs kasaya google.com`

**Comment by randilu** [comment]
@delanym 
The second argument here is preserved for scripts for more flexibilty. I would suggest you to use a script to achieve this.
ex:- `sample.kasaya` script
```
start
open "google.com"
end
```
- Save the script with `.kasaya` extension.
- Run script with `kasaya sample.kasaya` for global installations, OR `node kasaya sample.kasaya` for local installations.
