### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by amithamohan** [syscolabs/kasaya#2]
not able to install. Shows deprecated

**Comment by ifndev** [comment]
We can't guess neither what is happening, nor why it's happening. **Please provide your installation logs and give us more context.**

Keep in mind that each machine is different, so it may be possible that the problem isn't coming from kasaya.

[Requests is now deprecated](https://github.com/request/request/issues/3142), thus showing a warning during installation, but it should not prevent the package from being installed.

Next time you open an issue on github, **please take the time to [read this](https://wiredcraft.com/blog/how-we-write-our-github-issues/) before.**

**Comment by randilu** [comment]
Can you please provide `error logs` and more context?
