### ISSUE TITLE
Looking at the demo video I see this tool is has long way to go comparing the tools available in the market. 

### ISSUE THREAD

**Issue by lkkushan101** [syscolabs/kasaya#21]
Here are my questions 
1. When we run automation scripts we don't type the scripts manually on the IDE while executing. If so its better to do manual testing
2. This runs on a single browser where tools available in the market today can run on multiple browsers. 
3. I see in the video that you type on the google search page which has the search input field but there are issues when you type a form which has multiple input fields ? Then you need to provide locators. 
4. Seems this uses Selenium and its a wrapper tool. But what about data driven and page object support. What this can support better than WebDriverIO and Cypress (Which has their own execution engine).  
5. So if we have multiple Inputs and check boxes how you guys handle them without using XPath and HTML IDs 
6. What about CI integration if scripts are written run time... 

When comparing this tool with ones that is available in the market there is long way to go...

**Comment by hliyan** [comment]
Please refer to the README.

**Comment by lkkushan101** [comment]
I have read the ReadMe.... but these are points thats is lacking in this tool
