### ISSUE TITLE
Execute script not work (Mac OS)

### ISSUE THREAD

**Issue by lukaszkonraf** [syscolabs/kasaya#24]
On Mac OS I try to execute written script it don't execute. It open browser but now go to url. And in dress bar write : data:, and stop. 
(manually when I type command after command after initialize kasaya it all work)

**Comment by AshanthaLahiru** [comment]
@lukaszkonraf can you share the script?

**Comment by lukaszkonraf** [comment]
Sure it is very simple :

`start`
   ` open "google.com"`
   ` type "cars"`
 `   press enter`
` end`

And after :

`kasaya start.kasaya`

it open browser and show as below:

<img width="893" alt="aisssue" src="https://user-images.githubusercontent.com/61328564/75070968-aed26980-54f4-11ea-8c58-32b497d26819.png">

**Comment by lukaszkonraf** [comment]
I reinstall node and kasaya and it work now
