### ISSUE TITLE
Unable to get 'click' to work

### ISSUE THREAD

**Issue by mthompson36** [syscolabs/kasaya#25]
I'm getting `Cannot perform the mouse action on 'Sign In', maybe use 'inspect' to check whether you are clicking on a valid element.`
Using the following code:
start
 open "https://www.zipstg.com/"
 click "Sign In"
end
I installed jarvis just fyi.  Any suggestions?
Thanks.

**Comment by hliyan** [comment]
I tried to recreate your problem, but I got this from cloudflare: "The owner of this website (www.zipstg.com) has banned your IP address". Any other way I can test it out?

**Comment by hliyan** [comment]
By the way, there is a "highlight" command that you can use to check if the element you want can be found on page (it will highlight in red) 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/6211831/75105767-9fab0300-563d-11ea-9bad-9609b498e90e.png">

**Comment by mthompson36** [comment]
This may have to do with our internal VPN access for this site.   I tried ev

**Comment by mthompson36** [comment]
That probably has to do with the site being an internal one. I have gotten it to work, not sure why it wasn't before. Thanks for getting back to me.
