### ISSUE TITLE
while loop?

### ISSUE THREAD

**Issue by fixerivan** [syscolabs/kasaya#26]
would be cool if there could be a while loop or any other form of loop to keep checking for smth on the page and only execute if a statement (check) is true

thx

**Comment by hliyan** [comment]
Hello, thanks for the feedback!

 Our current thinking is to keep this a testing language, so we're deliberately keeping conditionals and loops out. The idea is that if a conditional is required, it probably means you need two or more test scenarios. Ditto with loop. The other thing is, DSLs usually start going downhill when we try to add general programming language constructs, so we're keen to avoid that fate!

But for your case, there is already a capability:

> keep checking for smth on the page and only execute if a statement (check) is true

@randilu Can you direct @fixerivan to the right command? We should also  add it to the "commonly used commands" section.

Let us know if you have any other issues/suggestions.

**Comment by randilu** [comment]
@fixerivan 
You can use the explicit wait command to wait until a specific element is appeared on the page to execute the next command.

The syntax is as follows:
ex:-
```wait "5" seconds for "Hello"```

You can also check whether an element is displayed on the page using `check if` command.
ex:-
```check if "Hello" is available```

**Comment by mousehunter1121** [comment]
Closing since there are no other incoming suggestions on this.
