### ISSUE TITLE
Failed at the kasaya@0.1.2 postinstall script.

### ISSUE THREAD

**Issue by Yashodhara-cs** [syscolabs/kasaya#32]
When we try to install Kasaya [npm install -g kasaya] getting some Errors

Please find the Attachments for Error logs ,
Terminals image - ![Install-error](https://user-images.githubusercontent.com/53851006/75134346-01ce3b80-5704-11ea-9970-e61c42ed59e6.PNG)

Err-logs-file - [2020-02-24T07_06_00_993Z-debug.log](https://github.com/syscolabs/kasaya/files/4243403/2020-02-24T07_06_00_993Z-debug.log)

**Comment by hliyan** [comment]
See PR #33
