### ISSUE TITLE
Unable to read the value

### ISSUE THREAD

**Issue by sandhyaagarwal** [syscolabs/kasaya#38]
Hello,

I am trying to read a value from a certain column in a table. This is not a proper table but is rendered like a table. I am having great difficulty reading the value. Tried multiple options, to the left, to the right, near etc; I always end up with "No such a variable". Could you help ?

**Comment by AshanthaLahiru** [comment]
@sandhyaagarwal , You can achieve this by using grid search.

Ex:
```
read $searchText from row "Your row search text" column "Your column search text"
```

**Comment by sandhyaagarwal** [comment]
Can I search rows  / columns by index ? All the grid data is dynamic. I do not know which row I am looking for. I just want to find one row with a column containing a certain value. I tried multiple options, but I always see a "No such a variable" message. The grid is not a true grid in the sense that we have a table for the header and then another table for the rows etc; I tried using "near", "left", "right" etc; but it does not work.

**Comment by AshanthaLahiru** [comment]
@sandhyaagarwal At the moment, Kasaya doesn't allow to select rows and columns by index.

**Comment by sandhyaagarwal** [comment]
Thanks, @AshanthaLahiru.

**Comment by AshanthaLahiru** [comment]
Let us know if you need any more clarifications.

**Comment by sandhyaagarwal** [comment]
I am stuck as I do not know how to read a certain value from the page :-(

**Comment by sandhyaagarwal** [comment]
For "near", "top", "bottom" etc to work, should the elements be siblings / direct descendants etc; ? I have tried using these options too to look up a certain value but they are not working as expected.

**Comment by AshanthaLahiru** [comment]
@sandhyaagarwal , You don't need a perfect table to use grid search which I mentioned earlier.

> @sandhyaagarwal , You can achieve this by using grid search.
> 
> Ex:
> 
> ```
> read $searchText from row "Your row search text" column "Your column search text"
> ```

You just need two dimensional matrix layout.

**Comment by sandhyaagarwal** [comment]
Say, I want to fetch the value of the first row for a column, how do I do that ?

**Comment by hliyan** [comment]
@AshanthaLahiru sounds like a feature request. Maybe:

```
read $value from row number 1 column "Foo"
```

**Comment by sandhyaagarwal** [comment]
@hliyan I am really excited about Kasaya, I specially like that we don't have to know all those xpaths :-). Except for this issue which really caused a bit of frustration as I spent quite some time trying to get this working with different alternatives. 

Shouldn't any of these work as alternatives ?

read $value 0 to the bottom of "<columnname>"
read $value 0 near "<columnname>"

Any possibility that we can have the reading by row index and column index implemented soon ? or I can try doing it myself when possible :-). Thank you.

**Comment by AshanthaLahiru** [comment]
@hliyan , noted, will look into this.
