### ISSUE TITLE
cant type variables

### ISSUE THREAD

**Issue by fixerivan** [syscolabs/kasaya#5]
set $username to xyz

click Email
type $username

results in the string $username being imputed not the contents of the variable aka xyz

**Comment by ianleckey** [comment]
Have you tried type `'${username}'` ?

**Comment by fixerivan** [comment]
still no good

type '${username}'

results in the input box containing '${username}'

**Comment by randilu** [comment]
@fixerivan 
Currently the type command accepts only text as arguments and you can't provide variables.
So you can use `type "xyz"` command

**Comment by fixerivan** [comment]
ok thx, pls add this sometime when you have time would be a nice feature
