### ISSUE TITLE
Check for selenium installation before run

### ISSUE THREAD

**Issue by herlon214** [syscolabs/kasaya#6]
Hi, I don't have Selenium installed, would be nice if the initialization returns the error. Now it isn't returning anything:

```
[...] Initializing Kasāya...

[x] Something went wrong :(, would you like to try again! :)
```

**Comment by herlon214** [comment]
Actually I saw that you're using the `selenium-standalone`, so it should work. Maybe just check if it was started successfully or catch the error and show to the user

**Comment by randilu** [comment]
@herlon214 
Thanks for the suggestion. We will work on this...

**Comment by randilu** [comment]
Fixed with https://github.com/syscolabs/kasaya/pull/7
